# Generated by Django 2.1.1 on 2019-02-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_symbol',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=6),
        ),
    ]
