# Generated by Django 2.1.1 on 2019-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20190224_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_stockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_stock_symbol', models.CharField(choices=[('GOOGL', 'GOOGL'), ('INTL', 'INTL'), ('AAPL', 'AAPL'), ('AYI', 'AYI'), ('TSLA', 'TSLA'), ('GME', 'GME'), ('IBM', 'IBM'), ('GE', 'GE'), ('GT', 'GT'), ('BAC', 'BAC'), ('AMD', 'AMD'), ('F', 'F'), ('KHC', 'KHC'), ('T', 'T'), ('M', 'M'), ('CTL', 'CTL'), ('MSFT', 'MSFT'), ('AZO', 'AZO'), ('SJM', 'SJM'), ('AAP', 'AAP'), ('MAT', 'MAT'), ('EA', 'EA'), ('CPB', 'CPB'), ('KMX', 'KMX'), ('KEYS', 'KEYS'), ('JWN', 'JWN'), ('VMC', 'VMC'), ('OKE', 'OKE'), ('MOS', 'MOS'), ('KHC', 'KHC'), ('NEM', 'NEM'), ('TWTR', 'TWTR'), ('ABMD', 'ABMD'), ('DISCA', 'DISCA'), ('NBL', 'NBL'), ('DISCK', 'DISCK'), ('CAT', 'CAT')], default='INTL', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_symbol',
            field=models.CharField(max_length=6),
        ),
    ]
