# Generated by Django 2.1.1 on 2019-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190227_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_stockinfo',
            name='search_stock_symbol',
            field=models.CharField(choices=[('AAP', 'AAP'), ('AAPL', 'AAPL'), ('ABMD', 'ABMD'), ('AMD', 'AMD'), ('ANTM', 'ANTM'), ('AYI', 'AYI'), ('AZO', 'AZO'), ('BAC', 'BAC'), ('CAT', 'CAT'), ('CPB', 'CPB'), ('CTL', 'CTL'), ('DISCA', 'DISCA'), ('DISCK', 'DISCK'), ('EA', 'EA'), ('F', 'F'), ('GE', 'GE'), ('GME', 'GME'), ('GOOGL', 'GOOGL'), ('GT', 'GT'), ('IBM', 'IBM'), ('INTL', 'INTL'), ('JPM', 'JPM'), ('JWN', 'JWN'), ('KEYS', 'KEYS'), ('KHC', 'KHC'), ('KHC', 'KHC'), ('KMX', 'KMX'), ('LMT', 'LMT'), ('M', 'M'), ('MAT', 'MAT'), ('MOS', 'MOS'), ('MSFT', 'MSFT'), ('NBL', 'NBL'), ('NEM', 'NEM'), ('NOC', 'NOC'), ('OKE', 'OKE'), ('RTN', 'RTN'), ('SJM', 'SJM'), ('SNE', 'SNE'), ('T', 'T'), ('TGT', 'TGT'), ('TSLA', 'TSLA'), ('TWTR', 'TWTR'), ('VMC', 'VMC'), ('WMT', 'WMT')], default='INTL', max_length=6),
        ),
    ]
